from __future__ import annotations

from typing import Any

from copilot.daw.adapter import DawError

PROTOCOL_VERSION = "1"
BRIDGE_VERSION = "copilot-prelive-1"

CAPABILITIES = frozenset(
    {
        "health",
        "session.read",
        "session.transport",
        "track.create_midi",
        "track.delete",
        "track.rename",
        "track.volume",
        "track.mute",
        "clip.create",
        "clip.delete",
        "clip.rename",
        "clip.read_notes",
        "clip.write_notes",
        "clip.fire",
        "device.set_parameter",
        "device.load",
        "audio.capture_master",
    }
)

COMMAND_CAPABILITY = {
    "health_check": "health",
    "protocol_hello": "health",
    "get_session_info": "session.read",
    "get_playback_position": "session.read",
    "get_all_track_names": "session.read",
    "get_track_info": "session.read",
    "get_tracks_info": "session.read",
    "get_capture_topology": "session.read",
    "get_master_info": "session.read",
    "get_device_parameters": "session.read",
    "get_device_parameter": "session.read",
    "get_track_sends": "session.read",
    "browse_path": "session.read",
    "search_browser": "session.read",
    "create_midi_track": "track.create_midi",
    "delete_track": "track.delete",
    "set_track_name": "track.rename",
    "set_track_volume": "track.volume",
    "set_track_mute": "track.mute",
    "set_track_solo": "track.mute",
    "create_clip": "clip.create",
    "delete_clip": "clip.delete",
    "set_clip_name": "clip.rename",
    "get_clip_notes": "clip.read_notes",
    "add_notes_to_clip": "clip.write_notes",
    "fire_clip": "clip.fire",
    "fire_clips": "clip.fire",
    "stop_clip": "clip.fire",
    "stop_clips": "clip.fire",
    "set_device_parameter": "device.set_parameter",
    "set_device_parameters": "device.set_parameter",
    "load_instrument_or_effect": "device.load",
    "load_browser_item": "device.load",
    "load_browser_item_by_path": "browser.load",
    "delete_device": "device.load",
    "move_device": "device.load",
    "move_device_right": "device.load",
    "start_playback": "session.transport",
    "stop_playback": "session.transport",
    "set_current_song_time": "session.transport",
    "jump_to_time": "session.transport",
    "scrub_by": "session.transport",
    "continue_playing": "session.transport",
    "start_playback_at_qn": "session.transport",
    "set_arrangement_loop": "session.transport",
    "set_tempo": "session.transport",
    "create_audio_track": "track.create_midi",
    "get_available_inputs": "session.read",
    "get_available_outputs": "session.read",
    "get_track_input_routing": "session.read",
    "get_track_output_routing": "session.read",
    "get_track_available_input_types": "session.read",
    "get_track_available_output_types": "session.read",
    "get_session_automation_record": "session.read",
    "get_arrangement_length": "session.read",
    "get_current_song_time": "session.read",
    "get_clip_automation": "session.read",
    "set_track_input_routing": "track.mute",
    "set_track_output_routing": "track.mute",
    "set_device_input_routing": "device.set_parameter",
    "save": "session.transport",
    "set_track_monitoring": "track.mute",
    "get_track_monitoring": "session.read",
    "get_track_delay": "session.read",
    "get_session_path": "session.read",
    "set_track_arm": "track.mute",
    "set_send_level": "track.volume",
    "get_send_level": "session.read",
    "set_return_volume": "track.volume",
    "get_return_tracks": "session.read",
    "create_return_track": "track.create_midi",
    "create_group_track": "track.create_midi",
    "set_signature": "session.transport",
    "get_clip_warp_info": "session.read",
    "set_clip_warp_mode": "clip.write_notes",
    "create_audio_clip": "clip.create",
    "duplicate_clip_to_arrangement": "clip.create",
    "set_clip_warping": "clip.write_notes",
    "set_clip_loop": "clip.write_notes",
    "execute_mutation_batch": "compound.temporary_mutation",
    # Added for MCP whitelist parity (bridge command coverage).
    "add_warp_marker": "session.transport",
    "apply_groove": "session.transport",
    "capture_midi": "session.transport",
    "clear_clip_automation": "session.transport",
    "commit_groove": "session.transport",
    "create_locator": "session.transport",
    "create_scene": "session.transport",
    "delete_locator": "session.transport",
    "delete_return_track": "track.delete",
    "delete_scene": "session.transport",
    "delete_warp_marker": "clip.delete",
    "deselect_all_notes": "session.transport",
    "duplicate_clip": "clip.create",
    "duplicate_clip_loop": "clip.create",
    "duplicate_scene": "session.transport",
    "duplicate_track": "track.create_midi",
    "fire_scene": "clip.fire",
    "flatten_track": "session.transport",
    "focus_view": "session.transport",
    "fold_track": "session.transport",
    "freeze_track": "session.transport",
    "generate_bassline": "session.transport",
    "generate_drum_pattern": "session.transport",
    "get_device_by_name": "session.read",
    "get_groove_pool": "session.read",
    "get_rack_chains": "session.read",
    "humanize_clip_timing": "clip.write_notes",
    "humanize_clip_velocity": "clip.write_notes",
    "jump_to_cue_point": "session.transport",
    "jump_to_next_cue": "session.transport",
    "jump_to_prev_cue": "session.transport",
    "load_device_preset": "device.load",
    "move_clip_notes": "clip.write_notes",
    "move_device_left": "device.load",
    "quantize_clip": "clip.write_notes",
    "quantize_clip_notes": "clip.write_notes",
    "re_enable_automation": "session.transport",
    "redo": "session.transport",
    "remove_all_notes": "clip.write_notes",
    "remove_notes": "clip.write_notes",
    "select_clip": "session.transport",
    "select_device": "device.load",
    "select_rack_chain": "session.transport",
    "select_scene": "session.transport",
    "select_track": "session.transport",
    "set_arrangement_overdub": "session.transport",
    "set_clip_automation": "clip.write_notes",
    "set_clip_color": "clip.rename",
    "set_clip_end_marker": "clip.write_notes",
    "set_clip_end_time": "clip.write_notes",
    "set_clip_fade_in": "clip.write_notes",
    "set_clip_fade_out": "clip.write_notes",
    "set_clip_follow_action": "clip.write_notes",
    "set_clip_gain": "clip.write_notes",
    "set_clip_launch_mode": "clip.write_notes",
    "set_clip_launch_quantization": "clip.write_notes",
    "set_clip_notes": "clip.write_notes",
    "set_clip_pitch": "clip.write_notes",
    "set_clip_ram_mode": "clip.write_notes",
    "set_clip_start_marker": "clip.write_notes",
    "set_clip_start_time": "clip.write_notes",
    "set_clip_trigger_quantization": "clip.write_notes",
    "set_clip_velocity_amount": "clip.write_notes",
    "set_count_in_duration": "session.transport",
    "set_crossfader": "session.transport",
    "set_cue_volume": "session.transport",
    "set_detail_clip": "session.transport",
    "set_device_collapsed": "device.set_parameter",
    "set_draw_mode": "session.transport",
    "set_drum_pad_name": "session.transport",
    "set_drum_rack_pad_mute": "session.transport",
    "set_drum_rack_pad_solo": "session.transport",
    "set_exclusive_arm": "session.transport",
    "set_exclusive_solo": "session.transport",
    "set_follow_mode": "session.transport",
    "set_grid_quantization": "session.transport",
    "set_groove_amount": "session.transport",
    "set_metronome": "session.transport",
    "set_midi_recording_quantization": "session.transport",
    "set_overdub": "session.transport",
    "set_punch_in": "session.transport",
    "set_punch_out": "session.transport",
    "set_rack_macro": "device.set_parameter",
    "set_return_pan": "session.transport",
    "set_scene_color": "session.transport",
    "set_scene_name": "session.transport",
    "set_session_automation_record": "session.transport",
    "set_song_root_note": "session.transport",
    "set_swing_amount": "session.transport",
    "set_track_color": "track.rename",
    "set_track_crossfade_assign": "track.mute",
    "set_track_delay": "track.mute",
    "set_track_implicit_arm": "track.mute",
    "set_track_pan": "track.volume",
    "solo_exclusive": "clip.fire",
    "start_recording": "session.transport",
    "stop_all_clips": "session.transport",
    "stop_recording": "session.transport",
    "stop_scene": "clip.fire",
    "tap_tempo": "session.transport",
    "toggle_arrangement_record": "session.transport",
    "toggle_device": "device.set_parameter",
    "toggle_session_record": "session.transport",
    "transpose_notes": "clip.write_notes",
    "trigger_back_to_arrangement": "session.transport",
    "unarm_all": "clip.fire",
    "undo": "session.transport",
    "unfold_track": "session.transport",
    "ungroup_tracks": "session.transport",
    "unmute_all": "clip.fire",
    "unsolo_all": "clip.fire",

}

LOCAL_HOSTS = frozenset({"127.0.0.1", "localhost", "::1"})


class ProtocolError(DawError):
    pass


class UnsupportedCapability(DawError):
    pass


def require_local_host(host: str) -> None:
    if host not in LOCAL_HOSTS:
        raise DawError(
            f"LOCALHOST_TRUST_BOUNDARY: refusing non-local host {host!r}"
        )


def handshake_payload() -> dict[str, Any]:
    return {
        "protocol_version": PROTOCOL_VERSION,
        "bridge_version": BRIDGE_VERSION,
        "capabilities": sorted(CAPABILITIES),
        "bind": "127.0.0.1",
    }


def require_capability(capabilities: set[str], command_type: str) -> None:
    needed = COMMAND_CAPABILITY.get(command_type)
    if needed is None:
        raise UnsupportedCapability(f"Unknown command {command_type!r}")
    if needed not in capabilities:
        raise UnsupportedCapability(
            f"required capability {needed} not advertised for {command_type}"
        )
