"""Evidence-bound multi-element variation planning.

This module is deliberately a planner, not an analyzer and not a DAW writer.
It composes already persisted bass, drum-transient, and harmonic evidence into
one reviewable bundle. Missing evidence remains explicit instead of being
replaced with a generic musical template.
"""

from __future__ import annotations

from typing import Any, Literal
from pathlib import Path

from pydantic import BaseModel, ConfigDict, Field, model_validator

from copilot.integration.reference_variation_v1 import (
    ReferenceVariationError,
    build_reference_bound_bass_notes,
)
from copilot.schemas.harmonic_understanding import HarmonicUnderstanding
from copilot.schemas.music_analysis import MusicAnalysisPack
from copilot.schemas.musical_understanding import MusicalUnderstanding
from copilot.schemas.session import MidiNote


MULTI_ELEMENT_SCHEMA_VERSION = "multi-element-variation-v1"
SUPPORTED_ELEMENTS = ("BASS", "DRUMS", "HARMONIC")


class ElementPattern(BaseModel):
    model_config = ConfigDict(extra="forbid")

    role: Literal["BASS", "DRUMS", "HARMONIC"]
    status: Literal["EVIDENCE_BOUND", "INSUFFICIENT_EVIDENCE"]
    notes: list[MidiNote] = Field(default_factory=list)
    source_kind: str
    evidence_refs: list[str] = Field(default_factory=list)
    limitations: list[str] = Field(default_factory=list)
    transformation: str
    pitch_semantics: str


class MultiElementVariationBundle(BaseModel):
    model_config = ConfigDict(extra="forbid")

    schema_version: str = MULTI_ELEMENT_SCHEMA_VERSION
    status: Literal["READY", "PARTIAL", "ABSTAIN"]
    reference_id: str
    project_id: str
    start_qn: float = Field(ge=0)
    end_qn: float = Field(gt=0)
    variation_index: int = Field(ge=1, le=5)
    variation_count: int = Field(ge=1, le=5)
    elements: dict[str, ElementPattern]
    structure: dict[str, Any] = Field(default_factory=dict)
    evidence_refs: list[str] = Field(default_factory=list)
    limitations: list[str] = Field(default_factory=list)
    all_material_is_new: bool = True
    no_write: bool = True

    @model_validator(mode="after")
    def validate_contract(self) -> "MultiElementVariationBundle":
        if not self.no_write:
            raise ValueError("MULTI_ELEMENT_BUNDLE_MUST_BE_READ_ONLY")
        if self.end_qn <= self.start_qn:
            raise ValueError("MULTI_ELEMENT_REGION_INVALID")
        if not {"BASS", "DRUMS", "HARMONIC"}.issubset(self.elements):
            raise ValueError("MULTI_ELEMENT_REQUIRED_ROLES_MISSING")
        return self


def build_multi_element_variation_bundle(
    pack: MusicAnalysisPack,
    understanding: MusicalUnderstanding,
    *,
    start_qn: float,
    length_beats: float,
    variation_index: int = 1,
    variation_count: int = 1,
    harmonic_understanding: HarmonicUnderstanding | None = None,
) -> MultiElementVariationBundle:
    """Compose one bounded multi-element candidate from existing evidence.

    Bass is generated by the already validated reference-bound transform.
    Drums use only measured transient locations and intentionally retain a
    generic transient pitch because the source evidence does not identify
    kick/snare/hat roles. Harmonic notes are emitted only from selected chord
    hypotheses supplied by the persisted harmonic artifact.
    """
    if not pack.no_write or not understanding.no_write:
        raise ReferenceVariationError("MULTI_ELEMENT_SOURCE_MUST_BE_READ_ONLY")
    if harmonic_understanding is not None and not harmonic_understanding.no_write:
        raise ReferenceVariationError("MULTI_ELEMENT_HARMONY_MUST_BE_READ_ONLY")
    if variation_index < 1 or variation_index > variation_count or variation_count > 5:
        raise ReferenceVariationError("MULTI_ELEMENT_VARIATION_INDEX_INVALID")

    source_start = float(pack.timeline.get("start_qn") or 0.0)
    source_end = float(pack.timeline.get("end_qn") or 0.0)
    end_qn = start_qn + length_beats
    if length_beats <= 0 or start_qn < source_start or end_qn > source_end:
        raise ReferenceVariationError("MULTI_ELEMENT_REGION_OUT_OF_BOUNDS")

    bass_notes, bass_features = build_reference_bound_bass_notes(
        pack,
        understanding,
        start_qn=start_qn,
        length_beats=length_beats,
        variation_index=variation_index,
    )
    bass = ElementPattern(
        role="BASS",
        status="EVIDENCE_BOUND",
        notes=bass_notes,
        source_kind="ABLETON_MIDI",
        evidence_refs=list(bass_features.get("evidence_refs") or []),
        transformation=str(bass_features.get("variation_strategy") or "reference_bound_bass_transform"),
        pitch_semantics="SOURCE_EVIDENCED_BASS_PITCHES",
    )

    evidence_offset_qn = _infer_relative_evidence_offset(
        pack,
        understanding,
        harmonic_understanding,
    )
    drums = _build_drum_support(
        understanding,
        start_qn=start_qn,
        end_qn=end_qn,
        evidence_offset_qn=evidence_offset_qn,
    )
    harmonic = _build_harmonic_support(
        harmonic_understanding,
        reference_id=pack.reference_id,
        start_qn=start_qn,
        end_qn=end_qn,
        evidence_offset_qn=evidence_offset_qn,
    )
    elements = {"BASS": bass, "DRUMS": drums, "HARMONIC": harmonic}
    refs = list(dict.fromkeys(ref for element in elements.values() for ref in element.evidence_refs))
    limitations = list(dict.fromkeys(item for element in elements.values() for item in element.limitations))
    status = "READY" if all(item.status == "EVIDENCE_BOUND" for item in elements.values()) else "PARTIAL"
    return MultiElementVariationBundle(
        status=status,
        reference_id=pack.reference_id,
        project_id=pack.project_id,
        start_qn=start_qn,
        end_qn=end_qn,
        variation_index=variation_index,
        variation_count=variation_count,
        elements=elements,
        structure={
            "tempo_bpm": pack.tempo_bpm,
            "reference_window_bars": length_beats / 4.0,
            "section_labels": _section_labels(pack, start_qn, end_qn),
            "evidence_time_offset_qn": evidence_offset_qn,
        },
        evidence_refs=refs,
        limitations=limitations,
    )


def _build_drum_support(
    understanding: MusicalUnderstanding,
    *,
    start_qn: float,
    end_qn: float,
    evidence_offset_qn: float = 0.0,
) -> ElementPattern:
    events = [
        event
        for event in understanding.drums.transient_grid
        if start_qn <= event.grid.onset_qn + evidence_offset_qn < end_qn
    ]
    if not events:
        return ElementPattern(
            role="DRUMS",
            status="INSUFFICIENT_EVIDENCE",
            source_kind="DRUM_TRANSIENT_GRID",
            transformation="none",
            pitch_semantics="UNAVAILABLE",
            limitations=["NO_DRUM_TRANSIENTS_IN_REFERENCE_REGION"],
        )
    notes = [
        MidiNote(
            pitch=42,
            start_time=round(event.grid.onset_qn + evidence_offset_qn - start_qn, 4),
            duration=0.1,
            velocity=max(1, min(127, round(60 + min(float(event.strength), 1.0) * 60))),
        )
        for event in events
    ]
    return ElementPattern(
        role="DRUMS",
        status="EVIDENCE_BOUND",
        notes=notes,
        source_kind="DRUM_TRANSIENT_GRID",
        evidence_refs=list(dict.fromkeys(ref for event in events for ref in event.evidence_refs)),
        transformation="preserve_transient_locations_generic_percussion_pitch",
        pitch_semantics="GENERIC_TRANSIENT_ONLY",
        limitations=["TRANSIENT_GRID_DOES_NOT_IDENTIFY_KICK_SNARE_OR_HAT_ROLE"],
    )


def _build_harmonic_support(
    harmonic: HarmonicUnderstanding | None,
    *,
    reference_id: str,
    start_qn: float,
    end_qn: float,
    evidence_offset_qn: float = 0.0,
) -> ElementPattern:
    if harmonic is None:
        return ElementPattern(
            role="HARMONIC",
            status="INSUFFICIENT_EVIDENCE",
            source_kind="HARMONIC_UNDERSTANDING",
            transformation="none",
            pitch_semantics="UNAVAILABLE",
            limitations=["HARMONIC_ARTIFACT_NOT_ATTACHED"],
        )
    if harmonic.reference_id != reference_id:
        raise ReferenceVariationError("MULTI_ELEMENT_HARMONY_REFERENCE_MISMATCH")
    windows = [
        window
        for window in harmonic.windows
        if window.selected is not None
        and window.end_qn + evidence_offset_qn > start_qn
        and window.start_qn + evidence_offset_qn < end_qn
    ]
    if not windows:
        return ElementPattern(
            role="HARMONIC",
            status="INSUFFICIENT_EVIDENCE",
            source_kind="HARMONIC_UNDERSTANDING",
            transformation="none",
            pitch_semantics="UNAVAILABLE",
            evidence_refs=list(harmonic.provenance.get("evidence_refs") or []),
            limitations=["NO_SELECTED_CHORD_HYPOTHESIS_IN_REFERENCE_REGION"],
        )
    notes: list[MidiNote] = []
    refs: list[str] = []
    for window in windows:
        chord = window.selected
        assert chord is not None
        window_start = window.start_qn + evidence_offset_qn
        window_end = window.end_qn + evidence_offset_qn
        local_start = max(start_qn, window_start) - start_qn
        local_end = min(end_qn, window_end) - start_qn
        duration = local_end - local_start
        if duration <= 0:
            continue
        refs.extend(window.evidence_refs)
        refs.extend(chord.evidence_refs)
        for pitch_class in chord.pitch_classes:
            pitch = _pitch_class_to_midi(pitch_class)
            if pitch is not None:
                notes.append(MidiNote(pitch=pitch, start_time=round(local_start, 4), duration=round(duration, 4), velocity=72))
    if not notes:
        return ElementPattern(
            role="HARMONIC",
            status="INSUFFICIENT_EVIDENCE",
            source_kind="HARMONIC_UNDERSTANDING",
            transformation="selected_chord_without_supported_pitch_classes",
            pitch_semantics="UNAVAILABLE",
            evidence_refs=list(dict.fromkeys(refs)),
            limitations=["SELECTED_CHORD_HAS_NO_SUPPORTED_PITCH_CLASSES"],
        )
    return ElementPattern(
        role="HARMONIC",
        status="EVIDENCE_BOUND",
        notes=notes,
        source_kind="HARMONIC_UNDERSTANDING",
        evidence_refs=list(dict.fromkeys(refs)),
        transformation="reference_selected_chord_pitch_classes_as_new_voicing",
        pitch_semantics="SELECTED_CHORD_PITCH_CLASSES",
        limitations=list(harmonic.limitations),
    )


def _infer_relative_evidence_offset(
    pack: MusicAnalysisPack,
    understanding: MusicalUnderstanding,
    harmonic: HarmonicUnderstanding | None,
) -> float:
    """Reconcile artifacts captured from the reference window's local zero.

    The authoritative bass pack keeps the Live-set QN origin (160 in the
    current source).  The persisted drum/harmony artifacts use the same
    reference region but serialize it from local QN zero.  Shift only when
    the evidence range proves that representation; never guess from names.
    """
    source_start = float(pack.timeline.get("start_qn") or 0.0)
    source_end = float(pack.timeline.get("end_qn") or 0.0)
    source_span = max(0.0, source_end - source_start)
    if source_start <= 0.0 or source_span <= 0.0:
        return 0.0
    observed: list[float] = [
        float(event.grid.onset_qn)
        for event in understanding.drums.transient_grid
    ]
    if harmonic is not None:
        observed.extend(float(window.end_qn) for window in harmonic.windows)
    if not observed:
        return 0.0
    if max(observed) <= source_span + 1e-6:
        return source_start
    return 0.0


def _pitch_class_to_midi(value: str) -> int | None:
    names = {"C": 0, "B#": 0, "C#": 1, "DB": 1, "D": 2, "D#": 3, "EB": 3, "E": 4,
             "FB": 4, "E#": 5, "F": 5, "F#": 6, "GB": 6, "G": 7, "G#": 8, "AB": 8,
             "A": 9, "A#": 10, "BB": 10, "B": 11, "CB": 11}
    pitch_class = names.get(str(value).strip().upper().replace("♯", "#").replace("♭", "B"))
    return None if pitch_class is None else 60 + pitch_class


def _section_labels(pack: MusicAnalysisPack, start_qn: float, end_qn: float) -> list[str]:
    return list(dict.fromkeys(
        window.section_label
        for window in pack.windows
        if window.end_beat > start_qn and window.start_beat < end_qn and window.section_label
    ))


def load_harmonic_understanding(path: Path | str) -> HarmonicUnderstanding:
    source = Path(path)
    if not source.is_file():
        raise ReferenceVariationError(f"HARMONIC_UNDERSTANDING_NOT_FOUND: {source}")
    try:
        return HarmonicUnderstanding.model_validate_json(source.read_text(encoding="utf-8"))
    except Exception as exc:  # noqa: BLE001
        raise ReferenceVariationError(f"HARMONIC_UNDERSTANDING_INVALID: {source}") from exc


__all__ = [
    "ElementPattern",
    "MultiElementVariationBundle",
    "MULTI_ELEMENT_SCHEMA_VERSION",
    "SUPPORTED_ELEMENTS",
    "build_multi_element_variation_bundle",
    "load_harmonic_understanding",
]
