"""External source ingestion and specialist source-separation boundaries."""

from copilot.music_source.ingestion import (
    ExternalSourceCandidate,
    ExternalSourceDiscovery,
    ExternalSourceManifest,
    SourceDiscoveryStatus,
    discover_external_source,
    ingest_external_source,
)
from copilot.music_source.separation import (
    BSRoFormerInferProvider,
    DemucsInferProvider,
    SeparationBatch,
    SeparationRequest,
    SeparationStatus,
    SeparatedStem,
    SeparatorDescriptor,
)
from copilot.music_source.benchmark import (
    BlindCandidateMapping,
    CandidateDisposition,
    HumanStemEvaluation,
    SeparatorCheckpointManifest,
    SeparatorManifest,
    SeparatorRunRequest,
    SeparatorRuntimeManifest,
    StemBenchmarkManifest,
    StemCandidate,
    StemCandidateSet,
    StemSelectionDecision,
    TechnicalStemValidation,
    WeightsLicenseStatus,
    build_blind_bundle,
    build_stem_candidate_set,
    validate_stem_file,
)
from copilot.music_source.stem_reference import (
    STEM_REFERENCE_ANALYSIS_VERSION,
    STEM_ROLES,
    StemReferenceAnalysis,
    StemReferenceArtifact,
    StemReferenceObservation,
    StemReferenceRoleAnalysis,
    render_stem_reference_report,
    run_stem_reference_pipeline,
)

__all__ = [
    "ExternalSourceCandidate",
    "ExternalSourceDiscovery",
    "ExternalSourceManifest",
    "SourceDiscoveryStatus",
    "discover_external_source",
    "ingest_external_source",
    "BSRoFormerInferProvider",
    "DemucsInferProvider",
    "SeparationBatch",
    "SeparationRequest",
    "SeparationStatus",
    "SeparatedStem",
    "SeparatorDescriptor",
    "BlindCandidateMapping",
    "CandidateDisposition",
    "HumanStemEvaluation",
    "SeparatorCheckpointManifest",
    "SeparatorManifest",
    "SeparatorRunRequest",
    "SeparatorRuntimeManifest",
    "StemBenchmarkManifest",
    "StemCandidate",
    "StemCandidateSet",
    "StemSelectionDecision",
    "TechnicalStemValidation",
    "WeightsLicenseStatus",
    "build_blind_bundle",
    "build_stem_candidate_set",
    "validate_stem_file",
    "STEM_REFERENCE_ANALYSIS_VERSION",
    "STEM_ROLES",
    "StemReferenceAnalysis",
    "StemReferenceArtifact",
    "StemReferenceObservation",
    "StemReferenceRoleAnalysis",
    "render_stem_reference_report",
    "run_stem_reference_pipeline",
]
